# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-16 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180116_1103'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set([('customerOrder', 'product')]),
        ),
    ]
